# Generated by Django 4.1.3 on 2022-11-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=20)),
                ('phone_no', models.SmallIntegerField(max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
